Anthonyxd22 patch 1
IAHispano/Applio-RVC-Fork pull request #95
Opened 2023-10-16 06:54 UTC by Anthonyxd22

Update install_Applio.sh macOS Features were introduced to modularize…
… the code and make it more readable Homebrew installation is done using a function to keep the script clean.

(New news for macOS)
Features were introduced to modularize the code and make it more readable.
Homebrew installation is done using a function to keep the script clean.
Python 3 installation is handled in a separate function.
The virtual environment creation/activation logic was moved to a function.
The main menu and ending functions were maintained, and the overall flow of the script was improved.
Greater speed to execute

2023-10-16 07:12 UTC, blaise-tk commented
Did you test it on Linux?

2023-10-16 08:52 UTC, Anthonyxd22 commented
<img width="1470" alt="Captura de pantalla 2023-10-04 a la(s) 4 47 43 a m" src="https://github.com/IAHispano/Applio-RVC-Fork/assets/144498068/f052ca21-f8f3-495e-afaa-774f46f9b55a">
Yes I was testing it for Linux just now and it is 100 percent executable I saw some improvements

2023-10-19 21:04 UTC, HyperChocolat commented
Amigo como te digo que este pr rompe con la compatibilidad para versiones antiguas de python y varias distribuciones de linux a la vez. mejor separa los scripts

2023-10-19 21:28 UTC, Anthonyxd22 commented
Si en proposito que lo hice fue para que lea con mas facilidad en codigo rvc y en unico error que hice fue   versiones antiguas de python y varias distribuciones

2023-10-19 21:36 UTC, Anthonyxd22 commented
Entonces en codigo que propocione esta aprobando o  optimizo  en codigo de go-applio.sh  para que lea mucho mejor en codigo?

2023-10-19 21:45 UTC, HyperChocolat commented
> Entonces en codigo que propocione esta aprobando o optimizo en codigo de go-applio.sh para que lea mucho mejor en codigo?

Parece que todo es correcto. Ojala funcione para Mac. en linux funciona (testeado en parabola la version mas reciente de python)
Solo espera a que un admin haga merge

2023-10-19 21:51 UTC, Anthonyxd22 commented
en mac si funciona  lo estuve probando  Y en linux lo probe pero por 1 hora no es mucho la verdad

2023-10-19 21:52 UTC, Anthonyxd22 commented
oh y tambien se me olvido Una mac de 2012 puede correr en local no solamente la m1 o m2! aunque en mi caso tengo la m2  Y mi amigo tiene una 2012XD

2023-10-20 00:04 UTC, HyperChocolat commented
> en mac si funciona lo estuve probando Y en linux lo probe pero por 1 hora no es mucho la verdad

si tienes fallos entonces es cosa de applio y no el instaler en ese caso

2023-10-31 21:52 UTC, aitronssesin commented
Estamos pensando en hacer le merge a esta pull request. ¿Has podido comprobar si todo está en orden? Nos gustaría asegurarnos de que todo funcione correctamente, pero el problema es que no tenemos acceso a sistemas Mac OS ni Linux para llevar a cabo pruebas, por lo que no podemos verificarlo por nuestra cuenta.

2023-10-31 23:10 UTC, HyperChocolat commented
> Estamos pensando en hacer le merge a esta pull request. ¿Has podido comprobar si todo está en orden? Nos gustaría asegurarnos de que todo funcione correctamente, pero el problema es que no tenemos acceso a sistemas Mac OS ni Linux para llevar a cabo pruebas, por lo que no podemos verificarlo por nuestra cuenta.

deja pruebo el script este rapido en linux. segun anthony funciona en MAC

2023-10-31 23:12 UTC, HyperChocolat requested changes
Hay un doble echo -e "\033]0;Applio - Installer\007" y #!bin/bash

2023-10-31 23:15 UTC, Anthonyxd22 commented
<img width="892" alt="Screenshot 2023-10-31 at 7 14 14 PM" src="https://github.com/IAHispano/Applio-RVC-Fork/assets/144498068/adf379b6-8546-44cf-b435-bd44d35beeff">
<img width="663" alt="Screenshot 2023-10-31 at 7 14 21 PM" src="https://github.c
<img width="657" alt="Screenshot 2023-10-31 at 7 14 38 PM" src="https://github.com/IAHispano/Applio-RVC-Fork/assets/144498068/750d311d-b73a-4a58-89b9-d7ba4f5d1217">
om/IAHispano/Applio-RVC-Fork/assets/144498068/c46e8d2c-71b5-46f5-81
<img width="777" alt="Screenshot 2023-10-31 at 7 14 43 PM" src="https://github.com/IAHispano/Applio-RVC-Fork/assets/144498068/f87d1d6f-d95f-4d37-b1ae-b29557766cd7">
22-2aa5b6ed38d3">

2023-10-31 23:15 UTC, HyperChocolat commented
Despues de eso los unicos posibles errores son de dependencias y configuraciones de python en cada sistema independiente pero $py deberia de hacerse cargo de lo segundo. falta un anuncio que advierta que se requiere python (y posiblemente ffmpeg)

2023-10-31 23:15 UTC, Anthonyxd22 commented
<img width="663" alt="Screenshot 2023-10-31 at 7 14 21 PM" src="https://github.com/IAHispano/Applio-RVC-Fork/assets/144498068/d240bdf9-61ae-4e37-8579-1677231f1d2a">

2023-10-31 23:16 UTC, Anthonyxd22 commented
<img width="606" alt="Screenshot 2023-10-31 at 7 16 23 PM" src="https://github.com/IAHispano/Applio-RVC-Fork/assets/144498068/3675031e-0aff-4b44-b184-2eb1ded55c8b">

2023-10-31 23:17 UTC, HyperChocolat commented
> <img alt="Screenshot 2023-10-31 at 7 14 21 PM" width="663" src="https://user-images.githubusercontent.com/144498068/279536169-d240bdf9-61ae-4e37-8579-1677231f1d2a.png">

tienes un pip al inicio de el code que no deberia estar ahi tambien, linea 18

2023-10-31 23:17 UTC, Anthonyxd22 commented
Lo en probando en linux y en mac es 100% funcional en ambas plataforma

2023-10-31 23:19 UTC, HyperChocolat commented
> Lo en probando en linux y en mac es 100% funcional en ambas plataforma

cambia las primeras 3 lineas y la linea 18 porfavor. si no no se instalara pip correctamente

2023-10-31 23:20 UTC, HyperChocolat commented
> Lo en probando en linux y en mac es 100% funcional en ambas plataforma lo de 18 linea es por que en mac no puede utilizarse esto pip pip install --upgrade pip Y lo cambie a esto pip3 install --upgrade pip

ya pero no debe de ir ahi. porque no actualizara nada en el venv

2023-10-31 23:23 UTC, Anthonyxd22 commented
Ya lo cambie

2023-10-31 23:24 UTC, HyperChocolat commented
no hablo de mover la version de pip. si no moverlo a la funcion de venv. todos los installers deben de mover venv. no el sistema en si. lo digo porque esa cosa puede dejar archivos no removibles o dificiles de ver en distros linux al igual que en macOS

2023-10-31 23:27 UTC, HyperChocolat commented
> Estamos pensando en hacer le merge a esta pull request. ¿Has podido comprobar si todo está en orden? Nos gustaría asegurarnos de que todo funcione correctamente, pero el problema es que no tenemos acceso a sistemas Mac OS ni Linux para llevar a cabo pruebas, por lo que no podemos verificarlo por nuestra cuenta.

para estas situaciones abre el code en github codespace. te dejara ejecutar applio en linux

2023-10-31 23:58 UTC, HyperChocolat commented
el instalador de python si dejalo fuera o si no instalara python con un code que es para ejecutarse despues de la install lol

2023-11-01 00:04 UTC, Anthonyxd22 commented
ahora si xD 
![Uploading Screenshot 2023-10-31 at 8.03.32 PM.png…]()

2023-11-01 00:06 UTC, HyperChocolat commented
yes sar

2023-11-01 00:07 UTC, Anthonyxd22 commented
una pregunta que es merge xD (disculpa es que soy nuevo en github xd no vi ningun tutorial )

2023-11-01 00:14 UTC, HyperChocolat commented
> una pregunta que es merge xD (disculpa es que soy nuevo en github xd jajja)

merge es como combinar. hablo de que ya se puede combinar applio con tu code metiendolo a el repositorio principal
puedes checar que significa cada cosa aca [Glosario](https://docs.github.com/es/get-started/quickstart/github-glossary) aunque es super larga

2023-11-01 00:16 UTC, Anthonyxd22 commented
> > una pregunta que es merge xD (disculpa es que soy nuevo en github xd jajja)
> 
> merge es como combinar. hablo de que ya se puede combinar applio con tu code metiendolo a el repositorio principal puedes checar que significa cada cosa aca [Glosario](https://docs.github.com/es/get-started/quickstart/github-glossary#merge) aunque es super larga

Gracias

2023-11-01 00:29 UTC, merged